/** Semantic colors available inside the opaque-origin Session Plugin document. */
export const sessionPluginThemeTokens = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "border",
  "input",
  "ring",
  "success",
  "attention",
  "warning",
  "destructive",
  "destructive-foreground",
  "composer",
] as const;
